### PR TITLE
25 changing navigation bar UI. Adding fixing for smaller screens

### LINKED ISSUE #25: Navigation menu improvements
Navigation menu improvements:
- items should not wrap to multiple rows
    - should use only one row
    - items should collapse into expandable menu when screen width is narrow
- Language chooser on mobile should collapse on medium screen (hamburger menu)

### PR DESCRIPTION
**Pull request by shailee-m**
closes #25

### CODE REVIEW

File: src/components/GeriLifeTopbar.vue [hunk 1]
```diff
@@ -1,66 +1,35 @@
...
-          @click="$router.push({ path: '/homes' })"
-          class="text-grey-7"
-          flat
-          :size="isSmOrAbove ? 'md' : 'xs'"
-          icon="fa fa-home"
+  <div>
+    <q-toolbar class="bg-grey-4">
+      <div class="row no-wrap" style="width: 100%">
+        <q-toolbar-title
+          @click="$route.path !== '/' && $router.push({ path: '/' })"
```
Comment (brylie) [inline src/components/GeriLifeTopbar.vue]: I'd prefer to not use this short-circuit approach. What happens when the router pushes the same route? What side effect are we mitigating?

File: src/components/GeriLifeTopbar.vue [hunk 2]
```diff
@@ -124,21 +109,50 @@ export default {
...
   computed: {
-    isSmOrAbove() {
-      return (
-        this.$q.screen.sm ||
-        this.$q.screen.md ||
-        this.$q.screen.lg ||
-        this.$q.screen.xl
-      );
+    isMdOrAbove() {
+      return this.$q.screen.md || this.$q.screen.lg || this.$q.screen.xl;
```
Comment (brylie) [inline src/components/GeriLifeTopbar.vue]: Please use the existing Quasar responsive classes (e.g. `gt-sm`):

https://quasar.dev/style/visibility#window-width-related

> You can also show some DOM element or component if it’s lower than one of the sizes. Same for greater than one of the sizes. Just attach lt- or gt- prefixes, which come from “lower than” and “greater than”. Example: lt-md (display on xs and sm only), lt-xl (display on xs, sm, md and lg windows only), gt-md (display on greater than medium windows: lg and xl).

**Review by brylie — CHANGES_REQUESTED** [review]

File: src/components/GeriLifeTopbar.vue [hunk 3]
```diff
@@ -1,66 +1,35 @@
...
+          <q-img
+            width="30px"
+            height="30px"
+            src="~assets/gerilife-logo.png"
+            alt=""
+          />
+          <span class="text-grey-7"> GeriLife<sup>®</sup></span>
+        </q-toolbar-title>
+        <div class="col-8">
+          <div v-if="!!getCookie('token') && isMdOrAbove">
```
Comment (brylie) [inline src/components/GeriLifeTopbar.vue]: This `div seems superfluous. I.e. the `v-if` statement would be fine to apply on the parent div. Is there a specific reason that we need to apply the `col-8` class on a separate DOM element, or can we just combine the two elements into a single div?

**Review by brylie — CHANGES_REQUESTED** [review]

File: src/components/GeriLifeTopbar.vue [hunk 4]
```diff
@@ -1,66 +1,35 @@
...
+              @click="clicked(menuItem, index)"
+            >
+              <span class="q-ml-sm">{{ menuItem.title }}</span>
+            </q-btn>
+          </div>
+        </div>
       </div>
-      <q-space />
-      <div class="col-3 col-md-1">
+      <div style="max-width: 150px">
```
Comment (brylie) [inline src/components/GeriLifeTopbar.vue]: Is this inline style necessary? Could we use an existing responsive class rather than a hard-coded pixel value? E.g. the `col-3 col-md-1` seemed fine.

File: src/components/GeriLifeTopbar.vue (hunk 1 above)
Comment (brylie) [reply src/components/GeriLifeTopbar.vue]: Relatedly, let's use the declarative `router-link` approach, rather than imperative `router.push`:

https://router.vuejs.org/api/#router-link

File: src/components/GeriLifeTopbar.vue [hunk 5]
```diff
@@ -124,21 +109,50 @@ export default {
...
+        },
+        {
+          icon: "fa fa-cog",
+          title: this.$i18n.t("mainLayoutNavbar-settingsLink"),
+          route: "/settings",
+        },
+        {
+          icon: "fa fa-user",
+          title: this.$i18n.t("mainLayoutNavbar-profileLink"),
+          isProfileLink: true,
```
Comment (brylie) [inline src/components/GeriLifeTopbar.vue]: Let's use named routes:

https://router.vuejs.org/api/#router-construction-options

File: src/components/GeriLifeTopbar.vue [hunk 6]
```diff
@@ -152,9 +166,20 @@ export default {
...
     },
 
+    clicked(menuItem) {
+      this.selected = menuItem.title;
+      if (menuItem.isProfileLink) {
+        this.openProfile = true;
+      } else {
+        this.$router.push({ path: menuItem.route });
+      }
+    },
```
Comment (brylie) [inline src/components/GeriLifeTopbar.vue]: This function is probably redundant if we use router links for the menu items.

Go ahead and separate the profile link/button from the other navigation links, since it isn't behaving the same.

File: src/components/GeriLifeTopbar.vue [hunk 7]
```diff
@@ -72,43 +41,59 @@
...
+              <q-item-section avatar>
+                <q-icon :name="menuItem.icon" />
+              </q-item-section>
+              <q-item-section>
+                {{ menuItem.title }}
+              </q-item-section>
+            </q-item>
+            <q-separator :key="'sep' + index" v-if="menuItem.separator" />
+          </template>
+        </q-list>
```
Comment (brylie) [inline src/components/GeriLifeTopbar.vue:106]: Just add the profile link here as a separate entity.

Comment (brylie) [reply src/components/GeriLifeTopbar.vue:106]: E.g. we can use the `q-dialogue` prompt:

https://quasar.dev/vue-components/dialog#usage

```html
    <q-dialog v-model="prompt" persistent>
      <q-card style="min-width: 350px">
        <q-card-section>
          <div class="text-h6">Your address</div>
        </q-card-section>

        <q-card-section class="q-pt-none">
          <q-input dense v-model="address" autofocus @keyup.enter="prompt = false" />
        </q-card-section>

        <q-card-actions align="right" class="text-primary">
          <q-btn flat label="Cancel" v-close-popup />
          <q-btn flat label="Add address" v-close-popup />
        </q-card-actions>
      </q-card>
    </q-dialog>
```

**Review by brylie — CHANGES_REQUESTED** [review]

File: src/components/GeriLifeTopbar.vue (hunk 7 above)
Comment (shailee-m) [reply src/components/GeriLifeTopbar.vue:106]: it is already there

File: src/components/GeriLifeTopbar.vue (hunk 6 above)
Comment (shailee-m) [reply src/components/GeriLifeTopbar.vue]: done

File: src/components/GeriLifeTopbar.vue (hunk 5 above)
Comment (shailee-m) [reply src/components/GeriLifeTopbar.vue]: Done. Using paths config

File: src/components/GeriLifeTopbar.vue (hunk 4 above)
Comment (shailee-m) [reply src/components/GeriLifeTopbar.vue]: yes, the v-select occupies free width. so it needs to be wrapped in a div with max width. Moved style to a class

**Review by brylie — APPROVED** [review]
